version: "3.0"
services:
  my-app:
    image: simple-spring-docker-app:latest
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/github/simple-spring-docker-app/logs/dev/:/logs/dev/
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD = password